server:
  port: 9090

spring:
  application:
    name: cloud-gateway-service

  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:2040
          predicates:
            - Path=/auth/**

        - id: inventory-service
          uri: http://localhost:2011
          predicates:
            - Path=/inventory/**

        - id: purchase-service
          uri: http://localhost:2021
          predicates:
            - Path=/purchases/**

        - id: billing-service
          uri: http://localhost:2013
          predicates:
            - Path=/billing/**

        - id: reporting-service
          uri: http://localhost:2024
          predicates:
            - Path=/report/**

        - id: product-service
          uri: http://localhost:2014
          predicates:
            - Path=/products/**

        - id: notification-service
          uri: http://localhost:2020
          predicates:
            - Path=/notification/**

        - id: user-service
          uri: http://localhost:2030
          predicates:
            - Path=/users/**

auth:
  service:
    url: http://localhost:2040             

jwt:
  secret: 9Jt1c7zP6QwV8Lr5xC6vK0Z4E2m7R8H9nFJ3S5aQ2Wk=
