apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-gateway-service
  namespace: store
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloud-gateway-service
  template:
    metadata:
      labels:
        app: cloud-gateway-service
    spec:
      containers:
        - name: cloud-gateway-service
          image: evanellenstore/cloud-gateway-service:latest
          ports:
            - containerPort: 9090
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: k8s
          volumeMounts:
            - name: config-volume
              mountPath: /config
      volumes:
        - name: config-volume
          configMap:
            name: cloud-gateway-config
