apiVersion: v1
kind: Service
metadata:
  name: cloud-gateway-service
  namespace: store
spec:
  type: ClusterIP
  selector:
    app: cloud-gateway-service
  ports:
    - port: 9090
      targetPort: 9090
